<a href="https://colab.research.google.com/github/khacthiennguyen/Northwest-Corner-Method/blob/main/Northwest_Corner_Method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Vi**

In [ ]:
import numpy as np

def taybac_algothims(cols, rows):
    cols = np.array(cols)
    rows = np.array(rows)
    #tạo ma trận tạm từ zeros, giá trị là int
    cot, dong = len(cols), len(rows)
    matran_output = np.zeros((cot, dong), dtype=int)

    i = j = 0
    # lặp xem có phải là hàng cuối cùng hoặc cột cuối cùng không
    while i < cot and j < dong:
        if i == cot - 1:
            number = rows[j]
        elif j == dong - 1:
            number = cols[i]
        else:
            number = min(cols[i], rows[j])

        matran_output[i, j] = number

        cols[i] -= number
        rows[j] -= number

        if cols[i] == 0:
            i += 1
        elif rows[j] == 0:
            j += 1

    return matran_output


In [ ]:
cols = [8, 5, 6, 3, 2, 7,31]
rows = [6, 4, 5, 5, 2, 9]

ketqua = taybac_algothims(cols, rows)
#thêm vào ma trận giá trị của cột và hàng từ dữ liệu
ketqua[-1, :] = rows #thêm vào dòng cuối ma trận
ketqua = np.insert(ketqua, 0, np.array(cols), axis=1) #nối vào ma trận trước cột đầu tiên

print(ketqua)

[[ 8  6  2  0  0  0  0]
 [ 5  0  2  3  0  0  0]
 [ 6  0  0  2  4  0  0]
 [ 3  0  0  0  1  2  0]
 [ 2  0  0  0  0  0  2]
 [ 7  0  0  0  0  0  7]
 [31  6  4  5  5  2  9]]


# **Eng**

In [ ]:
import numpy as np

def northwest_corner_optimized(supply, demand):
    supply = np.array(supply)
    demand = np.array(demand)

    num_sources, num_destinations = len(supply), len(demand)
    transport_matrix = np.zeros((num_sources, num_destinations), dtype=int)

    i = j = 0
    while i < num_sources and j < num_destinations:
        # Check if it's the last row or column
        if i == num_sources - 1:
            transport_amount = demand[j]
        elif j == num_destinations - 1:
            transport_amount = supply[i]
        else:
            transport_amount = min(supply[i], demand[j])

        transport_matrix[i, j] = transport_amount

        supply[i] -= transport_amount
        demand[j] -= transport_amount

        if supply[i] == 0:
            i += 1
        elif demand[j] == 0:
            j += 1

    return transport_matrix

# Sample data
supply = [8, 5, 6, 3, 2, 7,31]
demand = [6, 4, 5, 5, 2, 9]

transport_plan = northwest_corner_optimized(supply, demand)

# Append the remaining demand values to the last row
transport_plan[-1, :] = demand
transport_plan = np.insert(transport_plan, 0, np.array(supply), axis=1)
# Display the transport plan
print(transport_plan)

[[ 8  6  2  0  0  0  0]
 [ 5  0  2  3  0  0  0]
 [ 6  0  0  2  4  0  0]
 [ 3  0  0  0  1  2  0]
 [ 2  0  0  0  0  0  2]
 [ 7  0  0  0  0  0  7]
 [31  6  4  5  5  2  9]]
